export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const SET_USER_ACCOUNT = "SET_USER_ACCOUNT";
export const SET_PRANA_CONTRACT = "SET_PRANA_CONTRACT";
export const SET_PRANA_HELPER_CONTRACT = "SET_PRANA_HELPER_CONTRACT";

export const GET_COLLECTABLE_CONTENT = "GET_COLLECTABLE_CONTENT";
export const GET_RESALE_TOKENS = "GET_RESALE_TOKENS";
export const GET_RENT_TOKENS = "GET_RENT_TOKENS";

export const GET_MY_PUBLISHED_CONTENT = "GET_MY_PUBLISHED_CONTENT";
export const GET_MY_COLLECTED_TOKENS = "GET_MY_COLLECTED_TOKENS";
export const GET_MY_RENTED_TOKENS = "GET_MY_RENTED_TOKENS";
